import { Metadata } from "next";

export const metadata: Metadata = {
  title: "Projects",
  description: "Generated by create next app",
};

export default function ProjectsLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return <main className="flex-grow flex-shrink">{children}</main>;
}
