import "./globals.css";
import { Inter } from "next/font/google";
import Navbar from "./components/Navbar";
import { ReduxProvider } from "@/store/provider";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "DevExpo",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className="dark">
      <body className={`${inter.className} bg-white dark:bg-gray-900`}>
        <ReduxProvider>
          <Navbar selected="Home" />
          {children}
        </ReduxProvider>
      </body>
    </html>
  );
}
