export const metadata = {
  title: "Projects",
  description: "Generated by create next app",
};

export default function UserLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return <main className="flex-grow flex-shrink ">{children}</main>;
}
